Repository MREYE-LUMC/ZOSPy, pull requests merged in 2023-07, with the labels that each got.

#25 Explain deviations from SemVer in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#26 Initialize with fewer lines
  pyproject.toml
  tests/conftest.py
  tests/test_zpcore.py
  tox.ini
  zospy/zpcore.py
Labels: enhancement

#27 Scientific notation regular expression for get_number_field in polarization
  scripts/generate_test_reference_data/tests.yaml
  tests/analyses/test_polarization.py
  tests/data/reference/20.3.2-test_polarization.py-test_transmission_returns_correct_result[32x32-False-0.001-1-0-0].json
  tests/data/reference/20.3.2-test_polarization.py-test_transmission_returns_correct_result[32x32-False-0.001-1-0-0].zmx
  tests/data/reference/23.1.0-test_polarization.py-test_transmission_returns_correct_result[32x32-False-0.001-1-0-0].json
  tests/data/reference/23.1.0-test_polarization.py-test_transmission_returns_correct_result[32x32-False-0.001-1-0-0].zmx
  zospy/analyses/polarization.py
Labels: bug
