Repository MREYE-LUMC/ZOSPy, pull requests merged in 2024-12, with the labels that each got.

#95 Notebooks for publication in Medical Physics
  .gitignore
  docs/examples.md
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/1_raytracing.ipynb
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/2_analysis.ipynb
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/README.md
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/geometry.json
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/geometry_lamberth.json
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/input_output_angles.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/input_output_angles_lamberth.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/navarro_geometry.json
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/navarro_input_output_angles.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/navarro_ray_trace_results.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/ray_trace_results.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/data/ray_trace_results_lamberth.csv
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/helpers.py
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/requirements.txt
Labels: documentation, skip changelog

#98 New-style wavefront analyses
  tests/analyses/new/test_wavefront.py
  zospy/analyses/new/parsers/types.py
  zospy/analyses/new/wavefront/__init__.py
  zospy/analyses/new/wavefront/wavefront_map.py
Labels: skip changelog, open science fund

#101 Systemviewers fixes for older OpticStudio versions
  tests/analyses/new/test_systemviewers.py
  zospy/analyses/new/base.py
  zospy/analyses/new/parsers/types.py
Labels: skip changelog

#102 Fixed set_surface for object surface
  zospy/analyses/base.py
Labels: skip changelog
