Repository MREYE-LUMC/ZOSPy, pull requests merged in 2025-03, with the labels that each got.

#125 Functions for setting/getting field, wavelength and surface
  tests/analyses/test_base.py
  zospy/analyses/base.py
  zospy/analyses/extendedscene/geometric_image_analysis.py
  zospy/analyses/mtf/fft_through_focus_mtf.py
  zospy/analyses/mtf/huygens_mtf.py
  zospy/analyses/old/extendedscene.py
  zospy/analyses/old/wavefront.py
  zospy/analyses/physicaloptics/physical_optics_propagation.py
  zospy/analyses/psf/huygens_psf.py
  zospy/analyses/raysandspots/ray_fan.py
  zospy/analyses/raysandspots/single_ray_trace.py
  zospy/analyses/reports/cardinal_points.py
  zospy/analyses/wavefront/wavefront_map.py
  zospy/analyses/wavefront/zernike_standard_coefficients.py
Labels: skip changelog

#131 Prevent a second initialization of ZOS
  tests/test_zpcore.py
  zospy/zpcore.py
Labels: bug, skip changelog, open science fund

#136 Replace changed files action with own solution
  .github/workflows/ci.yml
Labels: skip changelog

#138 Small documentation fixes
  docs/index.md
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/1_raytracing.ipynb
  examples/Patient-specific mapping of fundus photographs to three-dimensional ocular imaging/2_analysis.ipynb
Labels: documentation, skip changelog
